# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

inhibit_all_warnings!
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'DavidSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DavidSwiftDemo
  pod 'Alamofire'
  pod 'swiftScan'
  pod 'ESTabBarController'
  pod 'SwiftTheme'
  pod 'FSPagerView'
  pod 'ReachabilitySwift'
  pod 'Toaster'
  pod 'IQKeyboardManagerSwift'

  target 'DavidSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DavidSwiftDemoUITests' do
    # Pods for testing
  end

end
